adds sample calls for batch payment methods
XeroAPI/xero-node-oauth2-app pull request #83
Opened 2022-09-01 23:37 UTC by tnzzz

Examples of the following methods added:
- `createBatchPaymentHistoryRecord`
- `getBatchPayment`
- `deleteBatchPayment`
- `deleteBatchPaymentByURLParam`
- `getBatchPaymentHistory`

2022-09-06 23:30 UTC, RettBehrens commented on src/app.ts
> +import { BatchPaymentDelete, BatchPaymentDeleteByUrlParam, HistoryRecord, RepeatingInvoices, Schedule, TokenSetParameters } from 'xero-node'
Anything from the Accounting API, please import from xero-node below. Notice that anything from the other API sets have to be imported from their respective models

2022-09-06 23:30 UTC, RettBehrens commented on src/app.ts
> +import { create } from "domain";
If this is an unused import please remove

2022-09-06 23:31 UTC, RettBehrens requested changes
please see comments

2022-09-07 02:20 UTC, tnzzz reviewed
Lines 2702 - 2703 are as below:

`// since we already have an Employee model in the Accounting API scope, we've imported and renamed like so:`
` // import { Employee as AUPayrollEmployee } from 'xero-node/dist/gen/model/payroll-au/models';`

Should this import statement be moved to the top? Or should all import statements relating to commented out code be moved to where it is referenced?

2022-09-12 18:45 UTC, RettBehrens reviewed
Looks good to me. The only question I have is about the changes to package-lock.json, looks like lots of subtractions?

2022-09-13 01:44 UTC, tnzzz commented
> Looks good to me. The only question I have is about the changes to package-lock.json, looks like lots of subtractions?

I think I only ran `npm install` when I committed my initial changes, so I didn't delete delete `node_modules`. In my latest commit I have done both steps, but we've ended up with more deletions? The app itself still runs fine though 🤔

2022-09-14 22:08 UTC, RettBehrens approved these changes

2022-09-14 22:18 UTC, merged